/**
 * @file unique_id_assignment.cpp
 * Generated by VisibleSim BlockCode Generator
 * https://services-stgi.pu-pm.univ-fcomte.fr/visiblesim/generator.php#
 * @author Hovhannes STEPANYAN
 * @date 17-11-2022
 **/

#include <iostream>

#include "unique_id_assignmentCode.hpp"

using namespace std;
using namespace BlinkyBlocks;

int main(int argc, char** argv) {
    try {
        createSimulator(argc, argv, Unique_ID_AssignmentCode::buildNewBlockCode);
        getSimulator()->printInfo();
        BaseSimulator::getWorld()->printInfo();
        deleteSimulator();
    } catch (std::exception const& e) {
        cerr << "Uncaught exception: " << e.what();
    }

    return 0;
}